=== SamuelCletoMalle/DAM/LenguajeDeMarcas/DTD/exam3evDAM.dtd
<!ELEMENT ies (alumnos|grupos)*>
        <!ATTLIST ies
                codcentro CDATA "[0-9]{8}">
        <!ELEMENT alumnos (alumno)*>
        <!ELEMENT alumno (nombreC|email|direccion|notaMedia|grupoMat)*>
        <!ATTLIST alumno
                necesidadesespaciales CDATA #REQUIRED
                nif CDATA #IMPLIED>
        <!ELEMENT nombreC (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT direccion (codPostal|provincia)*>
        <!ELEMENT codPostal (#PCDATA)>
        <!ELEMENT provincia (#PCDATA)>
        <!ELEMENT notaMedia (#PCDATA)>
        <!ELEMENT grupoMat (#PCDATA)>
        <!ELEMENT grupos (grupo)*>
        <!ELEMENT grupo (nombre|nivel)*>
        <!ATTLIST grupo
                id CDATA #IMPLIED>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT nivel (#PCDATA)>
        <!ATTLIST nivel
                tipo (CFGS | CFGM | FPBasica) #REQUIRED>

=== SamuelCletoMalle/DAM/LenguajeDeMarcas/XSD/iesXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ies SYSTEM "exam3evDAM.dtd">
<ies codcentro="2803094">
    <alumnos>
        <alumno nif="32334983B" necesidadesespaciales="false">
         <nombreC>José Manuel Perez</nombreC>
         <email>jperez@gmail.com</email>
         <direccion>
          <codPostal>28093 </codPostal>
          <provincia>Cadiz</provincia>
         </direccion>
         <notaMedia>4.10</notaMedia>
         <grupoMat>1DAM</grupoMat>
        </alumno>
        <alumno necesidadesespaciales="true">
          <nombreC> Ana Pérez</nombreC>
          <direccion>
              <provincia>Madrid</provincia>
              <codPostal>11012 </codPostal>
          </direccion>
          <notaMedia>7.23</notaMedia>
          <grupoMat>1DAM</grupoMat>
         </alumno>
      </alumnos>
    <grupos> 
        <grupo id="123">
            <nombre>1DAM</nombre>
            <nivel>CFGS</nivel>
        </grupo>
        <grupo>
            <nombre>1SMR</nombre>
            <nivel>CFGM</nivel>
        </grupo>
    </grupos>
</ies>
